### ISSUE TITLE
Building the application outside of NAV

### ISSUE THREAD

**Issue by arcuri82** [navikt/familie-ba-sak#2838]
Dear NAV Engineers,

  thanks for open-sourcing many of the apps you are developing. We are a group of academic researchers (located in Oslo) on Software Engineering, in particular automated verification of Web Services (if you are interested in more details, see [here](https://github.com/EMResearch/EvoMaster)).

For research, we wanted to investigate some of the systems developed at NAV, as they are open-source. However, it does not seem possible to build the systems, due to:

```
<repositories>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/navikt/familie-felles</url>
        </repository>
</repositories>
```

which blocks unauthorized accesses, and so few needed dependencies cannot be downloaded (e.g., ` nav-foedselsnummer:testutils:jar:1.0-SNAPSHOT.6`)

Is there any _read-only_ credentials that can  be used? 

Not sure if this is the right channel to discuss this, so let me know if you prefer to continue the conversation somewhere else. Of course, it is also completely understandable if you have no interest in this. In that case, please accept our apologies and close this ticket.

thanks

**Comment by stigebil** [comment]
Hello @arcuri82 

We are using Github package repository, so you only need to create yourself a Token with read:packages right
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token and add following to your .m2/settings.xml and make sure that your mvn uses this settings.xml

```
 <servers>
    <server>
        <id>github</id>
        <username>x-access-token</username>
        <password>ghp_your_pat_token_here</password>
    </server>
</servers>
```

**Comment by arcuri82** [comment]
@stigebil thx! it worked ;)
